version: "3.8"

services:
  microservice:
    container_name: microservice
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    ports:
      - "5000:5000"
      - "5555:5555"
      - "7070:7070"
    environment:
      - PORT=5000
    depends_on:
      - postgesql
      - rabbitmq
      - prometheus
      - grafana
      - jaeger
      - node_exporter
      - mongodb
    restart: always
    volumes:
      - ./:/app
    networks:
      - microservice_network

  postgesql:
    image: postgres:13-alpine
    container_name: microservice_postgesql
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - microservice_network

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./:/data/db

  rabbitmq:
    image: rabbitmq:3.6-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - microservice_network

  prometheus:
    container_name: prometheus_container
    image: prom/prometheus
    volumes:
      - ./docker/monitoring/prometheus-local.yml:/etc/prometheus/prometheus.yml:Z
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=20d'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - '9090:9090'
    networks:
      - microservice_network

  grafana:
    container_name: grafana_container
    image: grafana/grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: 1234
    volumes:
      - ./:/var/lib/grafana
    ports:
      - '3000:3000'
    networks:
      - microservice_network

  jaeger:
    container_name: jaeger_container
    restart: always
    image: jaegertracing/all-in-one:1.21
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411
    networks:
      - microservice_network

  node_exporter:
    container_name: node_exporter_container
    image: prom/node-exporter
    ports:
      - '9101:9100'
    networks:
      - microservice_network

networks:
  microservice_network:
    driver: bridge