// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc2 "github.com/JIeeiroSst/go-app/internal/email/delivery/grpc"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// EmailServiceClient is the client API for EmailService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EmailServiceClient interface {
	SendEmails(ctx context.Context, in *SendEmailRequest, opts ...grpc.CallOption) (*SendEmailResponse, error)
	FindEmailById(ctx context.Context, in *FindEmailByIdRequest, opts ...grpc.CallOption) (*FindEmailByIdResponse, error)
	FindEmailsByReceiver(ctx context.Context, in *FindEmailsByReceiverRequest, opts ...grpc.CallOption) (*FindEmailsByReceiverResponse, error)
}

type emailServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEmailServiceClient(cc grpc.ClientConnInterface) EmailServiceClient {
	return &emailServiceClient{cc}
}

func (c *emailServiceClient) SendEmails(ctx context.Context, in *SendEmailRequest, opts ...grpc.CallOption) (*SendEmailResponse, error) {
	out := new(SendEmailResponse)
	err := c.cc.Invoke(ctx, "/emailService.EmailService/SendEmails", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailServiceClient) FindEmailById(ctx context.Context, in *FindEmailByIdRequest, opts ...grpc.CallOption) (*FindEmailByIdResponse, error) {
	out := new(FindEmailByIdResponse)
	err := c.cc.Invoke(ctx, "/emailService.EmailService/FindEmailById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailServiceClient) FindEmailsByReceiver(ctx context.Context, in *FindEmailsByReceiverRequest, opts ...grpc.CallOption) (*FindEmailsByReceiverResponse, error) {
	out := new(FindEmailsByReceiverResponse)
	err := c.cc.Invoke(ctx, "/emailService.EmailService/FindEmailsByReceiver", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmailServiceServer is the server API for EmailService service.
// All implementations must embed UnimplementedEmailServiceServer
// for forward compatibility
type EmailServiceServer interface {
	SendEmails(context.Context, *SendEmailRequest) (*SendEmailResponse, error)
	FindEmailById(context.Context, *FindEmailByIdRequest) (*FindEmailByIdResponse, error)
	FindEmailsByReceiver(context.Context, *FindEmailsByReceiverRequest) (*FindEmailsByReceiverResponse, error)
	mustEmbedUnimplementedEmailServiceServer()
}

// UnimplementedEmailServiceServer must be embedded to have forward compatible implementations.
type UnimplementedEmailServiceServer struct {
}

func (UnimplementedEmailServiceServer) SendEmails(context.Context, *SendEmailRequest) (*SendEmailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendEmails not implemented")
}
func (UnimplementedEmailServiceServer) FindEmailById(context.Context, *FindEmailByIdRequest) (*FindEmailByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindEmailById not implemented")
}
func (UnimplementedEmailServiceServer) FindEmailsByReceiver(context.Context, *FindEmailsByReceiverRequest) (*FindEmailsByReceiverResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindEmailsByReceiver not implemented")
}
func (UnimplementedEmailServiceServer) mustEmbedUnimplementedEmailServiceServer() {}

// UnsafeEmailServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmailServiceServer will
// result in compilation errors.
type UnsafeEmailServiceServer interface {
	mustEmbedUnimplementedEmailServiceServer()
}

func RegisterEmailServiceServer(s grpc.ServiceRegistrar, srv *grpc2.EmailMicroservice) {
	s.RegisterService(&EmailService_ServiceDesc, srv)
}

func _EmailService_SendEmails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServiceServer).SendEmails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/emailService.EmailService/SendEmails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServiceServer).SendEmails(ctx, req.(*SendEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmailService_FindEmailById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindEmailByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServiceServer).FindEmailById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/emailService.EmailService/FindEmailById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServiceServer).FindEmailById(ctx, req.(*FindEmailByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmailService_FindEmailsByReceiver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindEmailsByReceiverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServiceServer).FindEmailsByReceiver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/emailService.EmailService/FindEmailsByReceiver",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServiceServer).FindEmailsByReceiver(ctx, req.(*FindEmailsByReceiverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EmailService_ServiceDesc is the grpc.ServiceDesc for EmailService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EmailService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "emailService.EmailService",
	HandlerType: (*EmailServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendEmails",
			Handler:    _EmailService_SendEmails_Handler,
		},
		{
			MethodName: "FindEmailById",
			Handler:    _EmailService_FindEmailById_Handler,
		},
		{
			MethodName: "FindEmailsByReceiver",
			Handler:    _EmailService_FindEmailsByReceiver_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "email.proto",
}
